2022-04-10 14:53:02,329 INFO    MainThread:16895 [wandb_setup.py:_flush():75] Loading settings from /share/etud/e2008984/.config/wandb/settings
2022-04-10 14:53:02,329 INFO    MainThread:16895 [wandb_setup.py:_flush():75] Loading settings from /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/settings
2022-04-10 14:53:02,329 INFO    MainThread:16895 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-10 14:53:02,329 INFO    MainThread:16895 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-10 14:53:02,330 INFO    MainThread:16895 [wandb_init.py:_log_setup():405] Logging user logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220410_145302-296n58qo/logs/debug.log
2022-04-10 14:53:02,330 INFO    MainThread:16895 [wandb_init.py:_log_setup():406] Logging internal logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220410_145302-296n58qo/logs/debug-internal.log
2022-04-10 14:53:02,330 INFO    MainThread:16895 [wandb_init.py:init():439] calling init triggers
2022-04-10 14:53:02,330 INFO    MainThread:16895 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-10 14:53:02,330 INFO    MainThread:16895 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 1i2y4cvp
2022-04-10 14:53:02,331 INFO    MainThread:16895 [wandb_run.py:finish():1539] finishing run vibferreira/master_thesis/1i2y4cvp
2022-04-10 14:53:02,331 INFO    MainThread:16895 [jupyter.py:save_history():429] not saving jupyter history
2022-04-10 14:53:02,331 INFO    MainThread:16895 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-10 14:53:02,332 INFO    MainThread:16895 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-04-10 14:53:02,332 INFO    MainThread:16895 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-10 14:53:02,340 INFO    MainThread:16895 [wandb_run.py:_restore():1674] restore
2022-04-10 14:53:02,797 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 697687
  total_bytes: 697687
}

2022-04-10 14:53:02,909 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 697687
  total_bytes: 697687
}

2022-04-10 14:53:03,111 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 697687
  total_bytes: 697687
}

2022-04-10 14:53:03,830 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 697687
  total_bytes: 703434
}

2022-04-10 14:53:03,934 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 697687
  total_bytes: 703434
}

2022-04-10 14:53:04,036 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 698608
  total_bytes: 703434
}

2022-04-10 14:53:04,140 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 703434
  total_bytes: 703434
}

2022-04-10 14:53:04,243 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 703434
  total_bytes: 703434
}

2022-04-10 14:53:04,346 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 703434
  total_bytes: 703434
}

2022-04-10 14:53:04,448 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 703434
  total_bytes: 703434
}

2022-04-10 14:53:04,550 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 703434
  total_bytes: 703434
}

2022-04-10 14:53:05,222 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 703434
  total_bytes: 703434
}

2022-04-10 14:53:05,658 INFO    MainThread:16895 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  media_count: 16
}
pusher_stats {
  uploaded_bytes: 703434
  total_bytes: 703434
}
local_info {
}

2022-04-10 14:53:06,813 INFO    MainThread:16895 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-04-10 14:53:06,814 INFO    MainThread:16895 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-04-10 14:53:06,821 INFO    MainThread:16895 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-04-10 14:53:06,828 INFO    MainThread:16895 [wandb_init.py:init():492] starting backend
2022-04-10 14:53:06,828 INFO    MainThread:16895 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-10 14:53:06,838 INFO    MainThread:16895 [backend.py:ensure_launched():219] starting backend process...
2022-04-10 14:53:06,890 INFO    MainThread:16895 [backend.py:ensure_launched():224] started backend process with pid: 17083
2022-04-10 14:53:06,893 INFO    MainThread:16895 [wandb_init.py:init():501] backend started and connected
2022-04-10 14:53:06,930 INFO    MainThread:16895 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-10 14:53:06,930 INFO    MainThread:16895 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-10 14:53:06,930 INFO    MainThread:16895 [wandb_init.py:init():565] updated telemetry
2022-04-10 14:53:07,018 INFO    MainThread:16895 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-10 14:53:07,896 INFO    MainThread:16895 [wandb_run.py:_on_init():1759] communicating current version
2022-04-10 14:53:07,959 INFO    MainThread:16895 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.14 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-10 14:53:07,959 INFO    MainThread:16895 [wandb_init.py:init():625] starting run threads in backend
2022-04-10 14:53:09,645 INFO    MainThread:16895 [wandb_run.py:_console_start():1733] atexit reg
2022-04-10 14:53:09,646 INFO    MainThread:16895 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-10 14:53:09,646 INFO    MainThread:16895 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-10 14:53:09,648 INFO    MainThread:16895 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-10 14:53:09,648 INFO    MainThread:16895 [wandb_init.py:init():664] run started, returning control to user process
