2022-04-27 19:13:22,544 INFO    MainThread:81746 [wandb_setup.py:_flush():75] Loading settings from /share/etud/e2008984/.config/wandb/settings
2022-04-27 19:13:22,544 INFO    MainThread:81746 [wandb_setup.py:_flush():75] Loading settings from /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/settings
2022-04-27 19:13:22,545 INFO    MainThread:81746 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-27 19:13:22,545 INFO    MainThread:81746 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-27 19:13:22,545 INFO    MainThread:81746 [wandb_init.py:_log_setup():405] Logging user logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220427_191322-3jn7yxp7/logs/debug.log
2022-04-27 19:13:22,545 INFO    MainThread:81746 [wandb_init.py:_log_setup():406] Logging internal logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220427_191322-3jn7yxp7/logs/debug-internal.log
2022-04-27 19:13:22,545 INFO    MainThread:81746 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7efd387eceb0>
2022-04-27 19:13:22,546 INFO    MainThread:81746 [wandb_init.py:init():439] calling init triggers
2022-04-27 19:13:22,546 INFO    MainThread:81746 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-27 19:13:22,546 INFO    MainThread:81746 [wandb_init.py:init():492] starting backend
2022-04-27 19:13:22,546 INFO    MainThread:81746 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-27 19:13:22,579 INFO    MainThread:81746 [backend.py:ensure_launched():219] starting backend process...
2022-04-27 19:13:22,599 INFO    MainThread:81746 [backend.py:ensure_launched():224] started backend process with pid: 82164
2022-04-27 19:13:22,601 INFO    MainThread:81746 [wandb_init.py:init():501] backend started and connected
2022-04-27 19:13:22,630 INFO    MainThread:81746 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-27 19:13:22,630 INFO    MainThread:81746 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-27 19:13:22,631 INFO    MainThread:81746 [wandb_init.py:init():565] updated telemetry
2022-04-27 19:13:22,941 INFO    MainThread:81746 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-27 19:13:24,000 INFO    MainThread:81746 [wandb_run.py:_on_init():1759] communicating current version
2022-04-27 19:13:24,070 INFO    MainThread:81746 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.15 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-27 19:13:24,070 INFO    MainThread:81746 [wandb_init.py:init():625] starting run threads in backend
2022-04-27 19:13:26,879 INFO    MainThread:81746 [wandb_run.py:_console_start():1733] atexit reg
2022-04-27 19:13:26,881 INFO    MainThread:81746 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-27 19:13:26,881 INFO    MainThread:81746 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-27 19:13:26,883 INFO    MainThread:81746 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-27 19:13:26,883 INFO    MainThread:81746 [wandb_init.py:init():664] run started, returning control to user process
2022-04-27 19:13:37,234 INFO    MainThread:81746 [wandb_watch.py:watch():47] Watching
2022-04-27 19:28:00,160 ERROR   MainThread:81746 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/share/etud/e2008984/miniconda3/envs/torch_env/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2022-04-27 19:44:51,899 INFO    MainThread:81746 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-27 19:44:51,900 INFO    MainThread:81746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-27 19:44:51,909 INFO    MainThread:81746 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-27 19:44:52,167 INFO    MainThread:81746 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-27 19:44:52,167 INFO    MainThread:81746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-27 19:44:52,170 INFO    MainThread:81746 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-27 19:44:52,173 INFO    MainThread:81746 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-27 19:44:52,173 INFO    MainThread:81746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-27 19:44:52,179 INFO    MainThread:81746 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-27 19:44:52,181 INFO    MainThread:81746 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-27 19:44:52,181 INFO    MainThread:81746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-27 19:44:52,187 INFO    MainThread:81746 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-27 19:44:52,192 INFO    MainThread:81746 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-27 19:44:52,192 INFO    MainThread:81746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-27 19:44:52,196 INFO    MainThread:81746 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-27 19:44:52,209 INFO    MainThread:81746 [wandb_setup.py:_flush():75] Loading settings from /share/etud/e2008984/.config/wandb/settings
2022-04-27 19:44:52,209 INFO    MainThread:81746 [wandb_setup.py:_flush():75] Loading settings from /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/settings
2022-04-27 19:44:52,209 INFO    MainThread:81746 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-27 19:44:52,209 INFO    MainThread:81746 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-27 19:44:52,210 INFO    MainThread:81746 [wandb_init.py:_log_setup():405] Logging user logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220427_194452-vuiqzu49/logs/debug.log
2022-04-27 19:44:52,210 INFO    MainThread:81746 [wandb_init.py:_log_setup():406] Logging internal logs to /share/mastoc/projects/erasmus/dl_historical_images/master_thesis/utils/wandb/run-20220427_194452-vuiqzu49/logs/debug-internal.log
2022-04-27 19:44:52,210 INFO    MainThread:81746 [wandb_init.py:init():439] calling init triggers
2022-04-27 19:44:52,210 INFO    MainThread:81746 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-04-27 19:44:52,210 INFO    MainThread:81746 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3jn7yxp7
2022-04-27 19:44:52,211 INFO    MainThread:81746 [wandb_run.py:finish():1539] finishing run vibferreira/master_thesis/3jn7yxp7
2022-04-27 19:44:52,211 INFO    MainThread:81746 [jupyter.py:save_history():429] not saving jupyter history
2022-04-27 19:44:52,212 INFO    MainThread:81746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-27 19:44:52,212 INFO    MainThread:81746 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-04-27 19:44:52,212 INFO    MainThread:81746 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-27 19:44:52,215 INFO    MainThread:81746 [wandb_run.py:_restore():1674] restore
2022-04-27 19:44:52,539 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 6375670
  total_bytes: 6386830
}

2022-04-27 19:44:52,668 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 6375670
  total_bytes: 6386830
}

2022-04-27 19:44:52,857 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 6378702
  total_bytes: 6386830
}

2022-04-27 19:44:53,116 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 6378702
  total_bytes: 6386830
}

2022-04-27 19:44:53,339 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 6378702
  total_bytes: 7224971
}

2022-04-27 19:44:53,443 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 6378702
  total_bytes: 7224971
}

2022-04-27 19:44:53,547 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 6387263
  total_bytes: 7224971
}

2022-04-27 19:44:53,653 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 6387263
  total_bytes: 7224971
}

2022-04-27 19:44:53,757 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7216466
  total_bytes: 7224971
}

2022-04-27 19:44:53,863 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7216466
  total_bytes: 7224971
}

2022-04-27 19:44:53,967 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224594
  total_bytes: 7224971
}

2022-04-27 19:44:54,071 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224594
  total_bytes: 7224971
}

2022-04-27 19:44:54,174 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224971
  total_bytes: 7224971
}

2022-04-27 19:44:54,277 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224971
  total_bytes: 7224971
}

2022-04-27 19:44:54,382 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224971
  total_bytes: 7224971
}

2022-04-27 19:44:54,487 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224971
  total_bytes: 7224971
}

2022-04-27 19:44:54,591 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224971
  total_bytes: 7224971
}

2022-04-27 19:44:55,767 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224971
  total_bytes: 7224971
}

2022-04-27 19:44:56,214 INFO    MainThread:81746 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  media_count: 1000
}
pusher_stats {
  uploaded_bytes: 7224971
  total_bytes: 7224971
}
local_info {
}

2022-04-27 19:44:57,501 INFO    MainThread:81746 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-04-27 19:44:57,534 INFO    MainThread:81746 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-04-27 19:44:57,541 INFO    MainThread:81746 [wandb_run.py:_footer_sync_info():2822] logging synced files
